### ISSUE TITLE
Provide a way to modify logging levels dinamically on browsers

### ISSUE THREAD

**Issue by lhrolim** [pimterry/loglevel#110]
On a modular nodejs project, in which each of the modules depend on loglevel, there´ll be several instances available.

It would be interesting if, from a single global configuration we could modify the behaviour of all of these loggers, dinamically, on a browser console.

One idea could be  the adoption of the localstorage so that we could call something such as:

sessionStorage.loglevel = 'debug'  --> Internally, the loglevel would then check for the presence of such variable each time in order to call the appropriate function.

sessionStorage["log_xxx"] = 'debug' could be used to set a level for a given logger.

Right now, the replaceLoggingMethods function, assigns a "noop" function, which do not allow for such dynamic level comparison.

I´m quite new to the project, so please let me know whether this doesn´t make sense or if there´s already a way of accomplishing that.

Thanks

**Comment by lhrolim** [comment]
Well, for the record, after digging, I realize I could accomplish something similar by doing:

localStorage.loglevel = 'DEBUG'

and refreshing the browser.

Not exactly as powerful, since I was thinking of ways of dinamically changing the levels, using a screen, for instance, but will help me a bit already.

**Comment by pimterry** [comment]
This isn't something loglevel can do directly because to preserve stacktraces correctly when logging, loglevel cannot wrap or add any of its own runtime behaviour to logging methods. As soon as you add any logic triggered by calls to `log.error`, or similar, you will lose the stack traces for those log messages. That means the below is impossible, without breaking stacktraces:

> Internally, the loglevel would then check for the presence of such variable each time in order to call the appropriate function.

The right solution to this, where possible, is to just share a single instance of the library. You mention nodejs - in a normal npm project, if you have multiple compatible dependencies on loglevel, they should be deduped, and you'll normally actually only end up with one instance anyway, which neatly solves this problem. You said:

> On a modular nodejs project, in which each of the modules depend on loglevel, there´ll be several instances available.

That shouldn't be true, in most normal usage. Are you sure this is what's happening in your system? Why?

Otherwise, your options are very limited - you can refresh the loglevel in localStorage, as you've found, but you need to reload the loglevel library somehow to pick up the change. Since there's no way you can get hold of the internal instance of the library from these other modules, there's no way you could ever trigger that though, other than a full process/browser refresh.

Generally, there's not much you can do here, and I'm inclined to say that that's fine. If you want to guarantee you'll be sharing a logging instances between modules, modules should intentionally expose that (e.g. take a `log` instance in a constructor). If modules don't want to expose their internal logging to external controls, there's really nothing you can do - its the same problem as if they were logging directly to the console themselves.

**Comment by pimterry** [comment]
There is actually a different alternative: it looks like there is a spec for storage events (https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-event), which would let loglevel automatically listen for localStorage changes, and then refresh itself. I'm potentially open to PRs adding that, but only if you can do so in a way that's reliable for much older browsers that don't support the spec. I have no idea how good modern browser support for this is either, so I don't know how useful that is to you.

If you control the modules that are using loglevel, you could easily do this yourself internally instead (listen for changes, call `log.setLevel(log.getLevel())`) which might be easier, since you know exactly which browsers you need to support.

**Comment by lhrolim** [comment]
Hi Tim, 

thanks for the feedback.

Actually, I´m no expert to nodejs development either, just getting started.

I believe the behaviour I saw, of non singletons modules was due to the presence of a local npm module (file:xxx) which creates a symbolic link in windows.

To clarify, my setup was as follows:

I have 2 projects (app and service). App depends on service.
At package.json of app I´m using file:../service, so that a symlink is generated to service module, so that I could easily debug both.

At both app and service codebases, I had files requiring loglevel.

At such setup, each of these requires, would return different instances.
Think this is due to https://stackoverflow.com/a/13181673/165622.

I´m saying that, because my first attempt was to export the require('loglevel') to a window.log variable which I could later easily control at the browser level, without having to restart the app.

With the localstorage key, though, I was able to do that and hit refresh, thus, changing the loglevel without having to modify the codebase, dinamically.

I´ll spend some time later reading the rest of your initial considerations of why it couldn´t be achieved. 

Thanks

**Comment by pimterry** [comment]
Ah, ok. Yes, for local development npm link and friends can cause interesting problems with duplicated modules like this. For that case, I think the way to do this totally reliably would be to make your service take a `log` parameter in some kind of initial setup constructor, and not depend on loglevel directly at all. That way the app provides and manages the log instance, and can guarantee that they're using the same instance, even when using npm link etc.

There might be other more general solutions to the problem though, I'm not sure. I know npm link has a few issues link this, where singleton behaviour can unexpectedly change. https://www.npmjs.com/package/dynamic-dedupe looks like it might be useful here, but I've never tried it, and it's nothing to do with loglevel specifically.

I'm going to close this ticket for now, but feel free to reopen if you think there's something specific loglevel needs to do to solve this.
