### ISSUE TITLE
Dont log anything

### ISSUE THREAD

**Issue by devvtms** [pimterry/loglevel#116]
Hy,
probably i misunderstand something... , i cant make logs with loglevel...

```js
// same as when use var log = require('loglevel');
import * as log from 'loglevel';
//....

render(){
    log.info("........................im here");
    log.debug("all done");
    //...
}
```

```
"dependencies": {
    "ajv": "^5.5.0",
    "ajv-errors": "^1.0.0",
    "auth0-js": "^8.11.3",
    "localforage": "^1.5.3",
    "loglevel": "^1.6.0",
    "prop-types": "^15.6.0",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^1.0.17",
//...
  }
```
nothing logged out, no errors...

**Comment by pimterry** [comment]
The default loglevel is `warn`, so info and debug messages are hidden. Try `log.setLevel('warn')`, or `log.warn('a message')`. Does that work for you?

**Comment by pimterry** [comment]
Sorry, that should have been `log.setLevel('debug')`

**Comment by devvtms** [comment]
thats intersting. i changed as you suggest , its working:
```js
import * as log from 'loglevel';
log.setLevel('debug')
//...
log.info("........................im here");
log.warn("all done");
```
 
still working when remove  `log.setLevel('debug')`, restart environment...

thank you for quick response :)

**Comment by pimterry** [comment]
Yes, that will still be working after you remove that line because by default loglevel persists your set level in your browser local storage (or cookies, if not available). If you clear your cookies or try incognito you'll go back to `warn` level, and these messages will disappear again.

I'd recommend setting a sensible default level in your code (try `log.setDefaultLevel('something')`) for whatever you're level you'd like to be visible normally, and then using `log.setLevel` yourself by hand when you need to make it louder/quieter for some specific debugging.

Anyway, glad your issue is sorted, let me know if you have any other trouble.
