### ISSUE TITLE
Import as ES6 module seems to break setLevel

### ISSUE THREAD

**Issue by anselanza** [pimterry/loglevel#127]
I am using the library in a project that transpiles NodeJS using Babel CLI.

Everything seems to be working normally, and the import statement works just fine, but `.setLevel` seems to be ignored.

```
import * as log from 'loglevel';
log.setLevel(log.levels.DEBUG);

console.log(log.getLevel()); // outputs 1, i.e. DEBUG
log.warn('always displayed'); // does output as expected
log.debug('hello?'); // no output!!

```

Curiously, in the above example, `log.getLevel()` returns the correct level, as if it has been changed properly, but subsequent calls to `log.debug` output nothing.

Without changing the transpiling setup, but just replacing the `import` with a `require`, I get different behaviour.

```
const log = require('loglevel');
log.setLevel(log.levels.DEBUG);

console.log(log.getLevel()); // outputs 1, i.e. DEBUG
log.warn('always displayed'); // does output as expected
log.debug('this works'); // does output as expected
```

Any ideas?

**Comment by pimterry** [comment]
It's hard to know from that description I'm afraid. That definitely sounds odd, but I'm not sure exactly what babel could be doing that would cause that.

Do you have an example available somewhere that I could use to easily reproduce this?

**Comment by pimterry** [comment]
Sadly that PR isn't correct, that's babel behaving debatably wrongly. `import log ...` is a default import, which should only work if this module exported a default explicitly (`exports.default = ...`), which it doesn't.

To be fair, the behaviour when mapping between ES6 modules & CommonJS isn't strictly defined, but in a full ES6 environment this wouldn't work without an explicit `export default` or similar, and because of that this doesn't work in other ES6 module environments like TypeScript.

As in [my last comment](https://github.com/pimterry/loglevel/pull/107#issuecomment-328680198) in that other PR: I would love some documentation updates here, but I don't want to go from wrong-for-some-people to wrong-for-other-people.

If you've got a little time though, I'd love somebody to go through and test a few ES6 environments and update the docs to say `For Babel: ..., For TS: ..., etc` so this is properly sorted out.

**Comment by anselanza** [comment]
Fair enough, and well explained.
