### ISSUE TITLE
current npm web page for loglevel shows no documentation at all

### ISSUE THREAD

**Issue by rretter** [pimterry/loglevel#176]
seems like the most recent release of loglevel into npm's reality didn't carry the README along with it, so far as npm's web page at https://www.npmjs.com/package/loglevel shows

**Comment by pimterry** [comment]
I'm not sure what you mean @rretter? I see the exact same content on https://www.npmjs.com/package/loglevel as in the README here: https://github.com/pimterry/loglevel#readme

**Comment by rretter** [comment]
interesting.  Chrome shows the page as you describe, but Brave (also
Chromium-based) does not (it shows the attached PNG).

could be either a Chrome/Brave difference (less likely) or some unintended
side effect of my browser settings in Brave (more likely).  since hunting
through browser settings to determine cause-and-effect is more fun than i
think i can stand (which you may agree with, if you've ever had to do it),
i leave it to your judgment as to whether it's worthwhile doing a quick
install of Brave, making no changes in it, and bringing up the web page.

please feel free to do whatever you'd like with the issue i reported.
thanks for your time.

**Comment by pimterry** [comment]
I have Brave installed already, and it shows fine there for me! I can't seem to reproduce this. I'm going go to assume it's something to do with your extensions or other configuration, but if you can find something specific in that page that's causing issues do let me know. I would suggest looking at the browser console for error messages there, since that often has clues to these kinds of problems.

I think I'd be quite surprised if this was broken in general though, since it's not doing anything special (it just shows the README markdown file directly from the package, exactly like every single other npm package) and I haven't heard other reports of issues, even though the last publish was months ago and this package gets millions of downloads a week. Can't be 100% sure, but do let me know if you manage to work out what's causing this.
