### ISSUE TITLE
Timestamp on logging

### ISSUE THREAD

**Issue by andreasi** [pimterry/loglevel#89]
Hi everyone.
We use the library for 4 months now and we are very satisfied with it. We came up with some logs on the console and we needed a timestamp for every log. The issue is that on chrome devtools you may enable the timestamp but when you save the logs as a .log file the timestamp is not saved. Is there a way that we can globally enable a timestamp on the library to prefix it when the library writes to console? Is there another issue already addressing this or something similar?
Thank you!

**Comment by pimterry** [comment]
Yes, you can do that, but it's not built into the library itself. The message-prefix plugin should do what you're looking for though: https://github.com/NatLibFi/loglevel-message-prefix.

This will have the side effect of messing up the stack traces in your developer console (they'll appear to come from inside that plugin, not directly from where you call log.error()). It's sadly not possible to both run code on demand when a logging method is called, e.g. to print the timestamp, and to also avoid that, which is why it's not available by default. There's some more detail in [the README](https://github.com/pimterry/loglevel#writing-plugins). You could look at only enabling the plugin when you know you need to save the logs though, if that's a problem for you.

Hope that helps! Note that I'm not the developer of the plugin, so you'll have to file issues over there if you have questions on exactly how it works. I'll close this for now, but happy to reopen it if you need a different approach.

**Comment by andreasi** [comment]
Unfortunately the use of the plugin produces some errors on the command line after the npm start script of our project.
This is the error
ERROR in ./~/json-loader!./~/loglevel-message-prefix/resources/parameters-schema.json
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (C:\Users\andreasi\My Projects\Logan\node_modules\json-loader\index.js:7:48)
 @ ./~/loglevel-message-prefix/lib/main.js 38:4-44:15

so we cannot use it for now. I'm going to address a new issue on the plugins github page. 
Thank you for your time
