### ISSUE TITLE
define.amd?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [pimterry/loglevel#95]
Hi, I'm using loglevel with emberjs, and It doesn't work, because of [this](https://github.com/pimterry/loglevel/blob/master/lib/loglevel.js#L9): `if (typeof define === 'function' && define.amd) {` 

I'm wondering why you are evaluating `define.amd`, is it really necessary? Without this validation, it works in ember. Thanks!

**Comment by pimterry** [comment]
That is the [canonical way](https://github.com/amdjs/amdjs-api/wiki/AMD#defineamd-property-) of testing for an AMD compatible module loader. If Ember's not exposing that, it's because it's not AMD-compatible (or at least, it's not trying to be), so loglevel shouldn't try and define itself as an AMD module. This might not work for your setup as-is, but it's definitely correct behaviour.

I don't know that much about Ember generally; when I've used it, it's been with ES6 module compilation, and using anything else has either required it be an ES6 module, or required that you make it global. What's your setup? What module loader/bundling are you using?
